### ISSUE TITLE
Multiformat spec for serialized cryptographic keys

### ISSUE THREAD

**Issue by littlebenlittle** [multiformats/multiformats#62]
Creating a multiformat for PKCS keys would future-proof serialized cryptographic key pairs. As quantum-computer resistant algorithms become more diverse and mature, it will be valuable to be able to store serialized keys that are self-describing.

Currently the type of key used in [Peer Ids and Keys](https://github.com/libp2p/specs/blob/6e109312b3e8a84e54ae15f12e764a0e97ab00cb/peer-ids/peer-ids.md#keys) is a codec-specific enum in the interface definition language. Because key data is not generally compressible due to its random nature, storing keys according to various codecs does not add value--at least as far as I can tell. Introducing a multiformat representation simplifies the serialization format and also does not preclude backwards-compatibility for CIDv1 PeerIds, as these can be built by parsing the keypair multiformat and generating the CID according the current [PeerId spec](https://github.com/libp2p/specs/blob/6e109312b3e8a84e54ae15f12e764a0e97ab00cb/peer-ids/peer-ids.md#peer-ids).

A suggestion for the general schema is

```
/ipfs/keypair/0.0.0/<pkcs identifier>/<multibase public key>/<multibase private key>
```

The PKCS identifier is a string describing the algorithm such as `rsa2048`, `ed25519`, [`ssi`](https://en.wikipedia.org/wiki/Supersingular_isogeny_key_exchange), [`ring-lwe`](https://en.wikipedia.org/wiki/Ring_learning_with_errors_key_exchange), etc. The public key and private key segments are multibase-encoded binary data and the private key is optional.

**Comment by rvagg** [comment]
I think the fact that protobuf is used in that spec is somewhat incidental and probably convenient due to the prevalence of protobuf in messaging protocols, _not_ for compressibility.

One advantage of that protobuf spec is that there are separate messages defined for public and private keys. What we absolutely don't want is a situation where accidental mixing and sharing of the two can occur. We need to avoid situations where private key could be shared because of a programmer misunderstanding about what's involved.

That's the big problem I can see with your proposal—they're easily mixed, and it would be trivial for a programmer to forget (or more likely: not realise) that this multiformats string is something that shouldn't leave the local device. Which brings up the second issue—is the utility of this thing reduced if it's simply a way of sharing pubkeys?

We have a (growing) list of public key formats in the multicodec table: https://github.com/multiformats/multicodec/blob/d70270706b60c6044a72e7f01050482f2ae1fd3f/table.csv#L89-L95

These could be used in various ways to identify public key data, including mushing them into a CID (probably not a great idea but people will do this anyway), or just base encoding a varint-prefixed pubkey.

So maybe you could outline use-cases where you see your proposed scheme to be offering value over what we already have, taking into account the importance of offering interfaces/tools to programmers that make it hard to accidentally share private keys?

**Comment by littlebenlittle** [comment]
Thanks for the feedback!

The use-case I am considering is the long-term storage of keys in persistent storage, such as `/etc/p2p-app/config.yaml` for most peers or a database for peers that manage multiple keys. Inclusion of key formats in the multicodec table should satisfy that need without the overhead of nesting them in a different codec.

```yaml
swarm:
  privateKey: kAbc...
  publicKey: k123...
```
