### ISSUE TITLE
C and Rust Implementation

### ISSUE THREAD

**Issue by kehiy** [multiformats/multiformats#70]
Hi, we are planning to Imlplement Multiformats using C (which is missed for most of multiformats) and Rust (which is missed for some of them). Can we have a repo on this organization to develop these implementations right here? or we can move implemented repos to this organization?

like: #35

**Comment by 0keeper1** [comment]
And I am ready to contribute ... 👍🏻

**Comment by rvagg** [comment]
No, sorry, having the repos in this org is a bit too awkward - it communicates a level of trust and authority that we are not in a position to grant since we can't be reviewing all of your work, and it puts us in a position of having to deal with longer-term maintenance concerns if you stop operating it. Instead, we've adopted a practice of liberally linking to implementations on the README of the spec repos, e.g.: https://github.com/multiformats/multihash?tab=readme-ov-file#implementations

But, I look forward to seeing your implementations! We have a lot of existing Rust work, but I'm not sure we have much mature C work and it'd be great to be able to add that to the list, I might even take a direct interest myself! Let us know if you need any help, guidance or we can point you to other resources.

**Comment by vmx** [comment]
There are already many things implemented for Rust (a multicodec table is missing intentionally). If there's anything else missing in the existing libraries that you need, please open issues on them an we can work something out. I prefer working together on implementations and sharing the maintenance work.
